ALTER TABLE sgp.equipo ADD COLUMN nombre VARCHAR(100) NOT NULL;
ALTER TABLE sgp.equipo ADD COLUMN estado TEXT NOT NULL;
ALTER TABLE sgp.equipo ADD COLUMN fechaAuditoria TIMESTAMP DEFAULT NULL;
ALTER TABLE sgp.equipo ADD COLUMN registroCertificacion VARCHAR(200) NOT NULL;